import mongoose, { Schema } from 'mongoose'

const itemStatSchema = Schema({
  _id: {
    type: Number,
    index: true
  },
  acc: Number,
  afterImage: Number,
  attackSpeed: Number,
  cash: Number,
  chatBalloon: Number,
  consumeHP: Number,
  consumeMP: Number,
  elemDefault: Number,
  expireOnLogout: Number,
  fs: Number,
  hide: Number,
  hpRecovery: Number,
  ignorePickup: Number,
  incACC: Number,
  incCraft: Number,
  incDEX: Number,
  incEVA: Number,
  incFatigue: Number,
  incINT: Number,
  incJump: Number,
  incLUK: Number,
  incMAD: Number,
  incMDD: Number,
  incMHP: Number,
  incMMD: Number,
  incMMP: Number,
  incPAD: Number,
  incPDD: Number,
  incRMAF: Number,
  incRMAI: Number,
  incRMAL: Number,
  incRMAS: Number,
  incSTR: Number,
  incSpeed: Number,
  incSwim: Number,
  islot: String,
  knockback: Number,
  longRange: Number,
  mpRecovery: Number,
  nameTag: Number,
  notSale: Number,
  only: Number,
  pachinko: Number,
  pickupItem: Number,
  pickupMeso: Number,
  pickupOthers: Number,
  price: Number,
  quest: Number,
  regPOP: Number,
  reqDEX: Number,
  reqINT: Number,
  reqJob: Number,
  reqLUK: Number,
  reqLevel: Number,
  reqPOP: Number,
  reqSTR: Number,
  sfx: Number,
  slotMax: Number,
  stand: Number,
  sweepForDrop: Number,
  tamingMob: Number,
  timeLimited: Number,
  tradeBlock: Number,
  tuc: Number,
  vslot: String,
  walk: Number
})

export default mongoose.model('ItemStats', itemStatSchema, 'itemStats')
