import mongoose, { Schema } from 'mongoose'

const monsterStatSchema = new Schema({
  _id: Number,
  acc: Number,
  bodyAttack: Number,
  boss: Number,
  buff: Number,
  chaseSpeed: Number,
  damagedByMob: Number,
  defaultHP: Number,
  defaultMP: Number,
  doNotRemove: Number,
  dropItemPeriod: Number,
  elemAttr: Number,
  eva: Number,
  exp: Number,
  explosiveReward: Number,
  firstAttack: Number,
  firstattack: Number,
  fixedDamage: Number,
  FlySpeed: Number,
  flySpeed: Number,
  flyspeed: Number,
  fs: Number,
  getCP: Number,
  hideHP: Number,
  hideName: Number,
  HPgaugeHide: Number,
  hpRecovery: Number,
  hpTagBgcolor: Number,
  hpTagColor: Number,
  invincible: Number,
  level: Number,
  link: Number,
  lnk: Number,
  MADamage: Number,
  maxHP: Number,
  maxMP: Number,
  mbookID: Number,
  MDDamage: Number,
  mobType: Number,
  mpRecovery: Number,
  noFlip: Number,
  noregen: Number,
  notAttack: Number,
  onlyNormalAttack: Number,
  PADamage: Number,
  PDDamage: Number,
  publicReward: Number,
  pushed: Number,
  removeAfter: Number,
  removeQuest: Number,
  speed: Number,
  summonType: Number,
  undead: Number
})

export default mongoose.model('MonsterStats', monsterStatSchema, 'monsterStats')
